spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:./securityjwtstudy
    username: sa
    password: '004637'
    driver-class-name: org.h2.Driver

  profiles:
    include: oauth

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400


  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            client-id: 528140661498-j21vs9lfflikqv66gil89b9up8ccrq7v.apps.googleusercontent.com
            scope: profile,email

logging.level:
  org.hibernate.SQL: debug